name: Heavy Tests

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    timeout-minutes: 20
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix develop --command \
            cargo integ-test -c "--release" -t heavy_tests -- --test-threads 1
