name: Per merge CI

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: "Format, docs, and lint"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: cargo fmt
        run: |
          nix develop --command \
            cargo fmt --all -- --check

      - name: cargo doc
        run: |
          nix develop --command \
            cargo doc --workspace --all-features --no-deps
      
      - name: cargo lint
        run: |
          nix develop --command \
            cargo lint
      
      - name: cargo test-lint
        run: |
          nix develop --command \
            cargo test-lint

  test:
    name: Unit Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: cargo test
        run: |
          nix develop --command \
            cargo test -- --include-ignored --nocapture
      
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: tarpaulin-report.html
      - uses: actions/upload-artifact@v3
        with:
          name: state-machine-coverage
          path: machine_coverage/

  integ-test:
    name: Integ tests
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: cargo integ-test
        run: |
          nix develop --command \
            cargo integ-test
